CREATE DATABASE doingsdone
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE UTF8_GENERAL_CI;
  
USE doingsdone;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dt_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email CHAR NOT NULL UNIQUE,
    name CHAR  NOT NULL,
    password CHAR  NOT NULL
);

CREATE TABLE project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title CHAR  NOT NULL UNIQUE,
    name_id INT  NOT NULL,
);

CREATE TABLE task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dt_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email CHAR NOT NULL UNIQUE,
    name CHAR  NOT NULL UNIQUE,
    password CHAR  NOT NULL UNIQUE,
    name_id INT  NOT NULL,
    title_project CHAR  NOT NULL UNIQUE
);